repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "8e87b31"
    hooks:
    -   id: autopep8

- repo: https://github.com/pycqa/isort
  rev: "5.12.0"
  hooks:
  - id: isort
    args: [ "--sl" ]
